<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADS40" name="Test" tests="21" failures="13" timestamp="30 Jun 2017 13:36:36 GMT" time="6.914" errors="0">
  <testcase name="HS_Contract_SchedRef_TC012" time="2.386" classname="exe.HS_Contract_SchedRef_Check_TS005">
    <failure type="com.mysql.jdbc.CommunicationsException" message="Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.&amp;lt;init&amp;gt;(Socket.java:434)
	at java.net.Socket.&amp;lt;init&amp;gt;(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.&amp;lt;init&amp;gt;(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.&amp;lt;init&amp;gt;(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC012(HS_Contract_SchedRef_Check_TS005.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


** END NESTED EXCEPTION **



Last packet sent to the server was 2 ms ago.">
      <![CDATA[com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC012(HS_Contract_SchedRef_Check_TS005.java:23)


** END NESTED EXCEPTION **



Last packet sent to the server was 2 ms ago.
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2847)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC012(HS_Contract_SchedRef_Check_TS005.java:23)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- HS_Contract_SchedRef_TC012 -->
  <testcase name="HS_Contract_SchedRef_TC013" time="2.008" classname="exe.HS_Contract_SchedRef_Check_TS005">
    <failure type="com.mysql.jdbc.CommunicationsException" message="Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.&amp;lt;init&amp;gt;(Socket.java:434)
	at java.net.Socket.&amp;lt;init&amp;gt;(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.&amp;lt;init&amp;gt;(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.&amp;lt;init&amp;gt;(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC013(HS_Contract_SchedRef_Check_TS005.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


** END NESTED EXCEPTION **



Last packet sent to the server was 0 ms ago.">
      <![CDATA[com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC013(HS_Contract_SchedRef_Check_TS005.java:52)


** END NESTED EXCEPTION **



Last packet sent to the server was 0 ms ago.
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2847)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC013(HS_Contract_SchedRef_Check_TS005.java:52)
... Removed 48 stack frames]]>
    </failure>
  </testcase> <!-- HS_Contract_SchedRef_TC013 -->
  <testcase name="HS_DBConnCheck_TC001" time="0.406" classname="exe.HS_ConnCheck_TS001"/>
  <testcase name="HS_InputFileExistance_TC002" time="0.502" classname="exe.HS_ConnCheck_TS001"/>
  <testcase name="HS_Record_Type_AS_Debt_Cancel_TC004" time="0.162" classname="exe.HS_Record_Type_DataValidation_TS003"/>
  <testcase name="HS_Record_Type_AS_Debt_Delinquent_Letter_TC005" time="0.118" classname="exe.HS_Record_Type_DataValidation_TS003"/>
  <testcase name="HS_Record_Type_AS_HS_DownGrade_TC006" time="0.118" classname="exe.HS_Record_Type_DataValidation_TS003">
    <failure type="junit.framework.AssertionFailedError" message="HS_DownGrade counts are Not Equal expected:&amp;lt;14&amp;gt; but was:&amp;lt;13&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: HS_DownGrade counts are Not Equal expected:<14> but was:<13>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Record_Type_DataValidation_TS003.HS_Record_Type_AS_HS_DownGrade_TC006(HS_Record_Type_DataValidation_TS003.java:141)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Record_Type_AS_HS_DownGrade_TC006 -->
  <testcase name="HS_Record_Type_AS_HS_Price_Increase_TC007" time="0.124" classname="exe.HS_Record_Type_DataValidation_TS003"/>
  <testcase name="HS_Record_Type_AS_NULL_TC008" time="0.178" classname="exe.HS_Record_Type_DataValidation_TS003"/>
  <testcase name="HS_Premise_Home_Phone_Check_TC013" time="0.148" classname="exe.HS_Phone_Number_Check_TS006"/>
  <testcase name="HS_Premise_Home_Phone_Check_TC014" time="0.079" classname="exe.HS_Phone_Number_Check_TS006">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Home_Phone_Number length not less than 10 Digits expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Home_Phone_Number length not less than 10 Digits expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Phone_Number_Check_TS006.HS_Premise_Home_Phone_Check_TC014(HS_Phone_Number_Check_TS006.java:61)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Home_Phone_Check_TC014 -->
  <testcase name="HS_Premise_Work_Phone_Check_TC015" time="0.02" classname="exe.HS_Phone_Number_Check_TS006">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Work_Phone_Number length not less than 10 Digits expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Work_Phone_Number length not less than 10 Digits expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Phone_Number_Check_TS006.HS_Premise_Work_Phone_Check_TC015(HS_Phone_Number_Check_TS006.java:90)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Work_Phone_Check_TC015 -->
  <testcase name="HS_Premise_Work_Phone_Check_TC016" time="0.028" classname="exe.HS_Phone_Number_Check_TS006">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Work_Phone_Number length not less than 10 Digits expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Work_Phone_Number length not less than 10 Digits expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Phone_Number_Check_TS006.HS_Premise_Work_Phone_Check_TC016(HS_Phone_Number_Check_TS006.java:119)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Work_Phone_Check_TC016 -->
  <testcase name="HS_Premise_Work_Phone_Check_TC017" time="0.13" classname="exe.HS_Phone_Number_Check_TS006"/>
  <testcase name="HS_Premise_First_Name_Check_TC018" time="0.04" classname="exe.HS_Premise_Name_Check_TS007">
    <failure type="junit.framework.AssertionFailedError" message="Premise_First_Name is Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;14&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_First_Name is Mandatory expected:<0> but was:<14>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Premise_Name_Check_TS007.HS_Premise_First_Name_Check_TC018(HS_Premise_Name_Check_TS007.java:32)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_First_Name_Check_TC018 -->
  <testcase name="HS_Premise_Last_Name_Check_TC019" time="0.046" classname="exe.HS_Premise_Name_Check_TS007">
    <failure type="junit.framework.AssertionFailedError" message="Premise_Last_Name is Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_Last_Name is Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Premise_Name_Check_TS007.HS_Premise_Last_Name_Check_TC019(HS_Premise_Name_Check_TS007.java:61)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_Last_Name_Check_TC019 -->
  <testcase name="HS_FileLevelRecCount_TC003" time="0.184" classname="exe.HS_RecCount_TS002">
    <failure type="junit.framework.AssertionFailedError" message="Row count Check Fail expected:&amp;lt;115&amp;gt; but was:&amp;lt;111&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Row count Check Fail expected:<115> but was:<111>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_RecCount_TS002.HS_FileLevelRecCount_TC003(HS_RecCount_TS002.java:68)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_FileLevelRecCount_TC003 -->
  <testcase name="HS_Mailing_City_Mandatory_Check_TC010" time="0.016" classname="exe.HS_Mandatory_Column_Check_TS004">
    <failure type="junit.framework.AssertionFailedError" message="Mailing_City is not Null | Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Mailing_City is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Mandatory_Column_Check_TS004.HS_Mailing_City_Mandatory_Check_TC010(HS_Mandatory_Column_Check_TS004.java:90)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Mailing_City_Mandatory_Check_TC010 -->
  <testcase name="HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011" time="0.028" classname="exe.HS_Mandatory_Column_Check_TS004">
    <failure type="junit.framework.AssertionFailedError" message="Partner_Account_Number is not Null or Length of Account number is not Correct expected:&amp;lt;0&amp;gt; but was:&amp;lt;21&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Partner_Account_Number is not Null or Length of Account number is not Correct expected:<0> but was:<21>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Mandatory_Column_Check_TS004.HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011(HS_Mandatory_Column_Check_TS004.java:119)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011 -->
  <testcase name="HS_Premise_City_Mandatory_Check_TC008" time="0.022" classname="exe.HS_Mandatory_Column_Check_TS004">
    <failure type="junit.framework.AssertionFailedError" message="Premise_City is not Null | Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_City is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Mandatory_Column_Check_TS004.HS_Premise_City_Mandatory_Check_TC008(HS_Mandatory_Column_Check_TS004.java:32)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_City_Mandatory_Check_TC008 -->
  <testcase name="HS_Premise_State_Mandatory_Check_TC009" time="0.03" classname="exe.HS_Mandatory_Column_Check_TS004">
    <failure type="junit.framework.AssertionFailedError" message="Premise_State is not Null | Mandatory expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Premise_State is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Mandatory_Column_Check_TS004.HS_Premise_State_Mandatory_Check_TC009(HS_Mandatory_Column_Check_TS004.java:61)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HS_Premise_State_Mandatory_Check_TC009 -->
</testsuite> <!-- Test -->
