<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="13" total="21" passed="8">
  <reporter-output>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
    <line>
      <![CDATA[Database Connection is Passed]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="6914" started-at="2017-06-30T13:36:29Z" finished-at="2017-06-30T13:36:36Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="6914" started-at="2017-06-30T13:36:29Z" finished-at="2017-06-30T13:36:36Z">
      <class name="exe.HS_Mandatory_Column_Check_TS004">
        <test-method status="FAIL" signature="HS_Mailing_City_Mandatory_Check_TC010()[pri:0, instance:exe.HS_Mandatory_Column_Check_TS004@61832929]" name="HS_Mailing_City_Mandatory_Check_TC010" duration-ms="16" started-at="2017-06-30T19:06:36Z" finished-at="2017-06-30T19:06:36Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Mailing_City is not Null | Mandatory expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Mailing_City is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Mandatory_Column_Check_TS004.HS_Mailing_City_Mandatory_Check_TC010(HS_Mandatory_Column_Check_TS004.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Mailing_City_Mandatory_Check_TC010 -->
        <test-method status="FAIL" signature="HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011()[pri:0, instance:exe.HS_Mandatory_Column_Check_TS004@61832929]" name="HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011" duration-ms="28" started-at="2017-06-30T19:06:36Z" finished-at="2017-06-30T19:06:36Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Partner_Account_Number is not Null or Length of Account number is not Correct expected:<0> but was:<21>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Partner_Account_Number is not Null or Length of Account number is not Correct expected:<0> but was:<21>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Mandatory_Column_Check_TS004.HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011(HS_Mandatory_Column_Check_TS004.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Partner_Account_Number_Mandatory_And_Length_Check_TC011 -->
        <test-method status="FAIL" signature="HS_Premise_City_Mandatory_Check_TC008()[pri:0, instance:exe.HS_Mandatory_Column_Check_TS004@61832929]" name="HS_Premise_City_Mandatory_Check_TC008" duration-ms="22" started-at="2017-06-30T19:06:36Z" finished-at="2017-06-30T19:06:36Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Premise_City is not Null | Mandatory expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Premise_City is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Mandatory_Column_Check_TS004.HS_Premise_City_Mandatory_Check_TC008(HS_Mandatory_Column_Check_TS004.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_City_Mandatory_Check_TC008 -->
        <test-method status="FAIL" signature="HS_Premise_State_Mandatory_Check_TC009()[pri:0, instance:exe.HS_Mandatory_Column_Check_TS004@61832929]" name="HS_Premise_State_Mandatory_Check_TC009" duration-ms="30" started-at="2017-06-30T19:06:36Z" finished-at="2017-06-30T19:06:36Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Premise_State is not Null | Mandatory expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Premise_State is not Null | Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Mandatory_Column_Check_TS004.HS_Premise_State_Mandatory_Check_TC009(HS_Mandatory_Column_Check_TS004.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_State_Mandatory_Check_TC009 -->
      </class> <!-- exe.HS_Mandatory_Column_Check_TS004 -->
      <class name="exe.HS_Record_Type_DataValidation_TS003">
        <test-method status="PASS" signature="HS_Record_Type_AS_Debt_Cancel_TC004()[pri:0, instance:exe.HS_Record_Type_DataValidation_TS003@26653222]" name="HS_Record_Type_AS_Debt_Cancel_TC004" duration-ms="162" started-at="2017-06-30T19:06:34Z" finished-at="2017-06-30T19:06:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Record_Type_AS_Debt_Cancel_TC004 -->
        <test-method status="PASS" signature="HS_Record_Type_AS_Debt_Delinquent_Letter_TC005()[pri:0, instance:exe.HS_Record_Type_DataValidation_TS003@26653222]" name="HS_Record_Type_AS_Debt_Delinquent_Letter_TC005" duration-ms="118" started-at="2017-06-30T19:06:34Z" finished-at="2017-06-30T19:06:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Record_Type_AS_Debt_Delinquent_Letter_TC005 -->
        <test-method status="FAIL" signature="HS_Record_Type_AS_HS_DownGrade_TC006()[pri:0, instance:exe.HS_Record_Type_DataValidation_TS003@26653222]" name="HS_Record_Type_AS_HS_DownGrade_TC006" duration-ms="118" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[HS_DownGrade counts are Not Equal expected:<14> but was:<13>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: HS_DownGrade counts are Not Equal expected:<14> but was:<13>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Record_Type_DataValidation_TS003.HS_Record_Type_AS_HS_DownGrade_TC006(HS_Record_Type_DataValidation_TS003.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Record_Type_AS_HS_DownGrade_TC006 -->
        <test-method status="PASS" signature="HS_Record_Type_AS_HS_Price_Increase_TC007()[pri:0, instance:exe.HS_Record_Type_DataValidation_TS003@26653222]" name="HS_Record_Type_AS_HS_Price_Increase_TC007" duration-ms="124" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Record_Type_AS_HS_Price_Increase_TC007 -->
        <test-method status="PASS" signature="HS_Record_Type_AS_NULL_TC008()[pri:0, instance:exe.HS_Record_Type_DataValidation_TS003@26653222]" name="HS_Record_Type_AS_NULL_TC008" duration-ms="178" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Record_Type_AS_NULL_TC008 -->
      </class> <!-- exe.HS_Record_Type_DataValidation_TS003 -->
      <class name="exe.HS_ConnCheck_TS001">
        <test-method status="PASS" signature="HS_DBConnCheck_TC001()[pri:0, instance:exe.HS_ConnCheck_TS001@29774679]" name="HS_DBConnCheck_TC001" duration-ms="406" started-at="2017-06-30T19:06:33Z" finished-at="2017-06-30T19:06:34Z">
          <reporter-output>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
            <line>
              <![CDATA[Database Connection is Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- HS_DBConnCheck_TC001 -->
        <test-method status="PASS" signature="HS_InputFileExistance_TC002()[pri:0, instance:exe.HS_ConnCheck_TS001@29774679]" name="HS_InputFileExistance_TC002" duration-ms="502" started-at="2017-06-30T19:06:34Z" finished-at="2017-06-30T19:06:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_InputFileExistance_TC002 -->
      </class> <!-- exe.HS_ConnCheck_TS001 -->
      <class name="exe.HS_Premise_Name_Check_TS007">
        <test-method status="FAIL" signature="HS_Premise_First_Name_Check_TC018()[pri:0, instance:exe.HS_Premise_Name_Check_TS007@5e5792a0]" name="HS_Premise_First_Name_Check_TC018" duration-ms="40" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Premise_First_Name is Mandatory expected:<0> but was:<14>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Premise_First_Name is Mandatory expected:<0> but was:<14>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Premise_Name_Check_TS007.HS_Premise_First_Name_Check_TC018(HS_Premise_Name_Check_TS007.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_First_Name_Check_TC018 -->
        <test-method status="FAIL" signature="HS_Premise_Last_Name_Check_TC019()[pri:0, instance:exe.HS_Premise_Name_Check_TS007@5e5792a0]" name="HS_Premise_Last_Name_Check_TC019" duration-ms="46" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:36Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Premise_Last_Name is Mandatory expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Premise_Last_Name is Mandatory expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Premise_Name_Check_TS007.HS_Premise_Last_Name_Check_TC019(HS_Premise_Name_Check_TS007.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_Last_Name_Check_TC019 -->
      </class> <!-- exe.HS_Premise_Name_Check_TS007 -->
      <class name="exe.HS_RecCount_TS002">
        <test-method status="FAIL" signature="HS_FileLevelRecCount_TC003()[pri:0, instance:exe.HS_RecCount_TS002@5b275dab]" name="HS_FileLevelRecCount_TC003" duration-ms="184" started-at="2017-06-30T19:06:36Z" finished-at="2017-06-30T19:06:36Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Row count Check Fail expected:<115> but was:<111>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Row count Check Fail expected:<115> but was:<111>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_RecCount_TS002.HS_FileLevelRecCount_TC003(HS_RecCount_TS002.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_FileLevelRecCount_TC003 -->
      </class> <!-- exe.HS_RecCount_TS002 -->
      <class name="exe.HS_Phone_Number_Check_TS006">
        <test-method status="PASS" signature="HS_Premise_Home_Phone_Check_TC013()[pri:0, instance:exe.HS_Phone_Number_Check_TS006@3ffc5af1]" name="HS_Premise_Home_Phone_Check_TC013" duration-ms="148" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_Home_Phone_Check_TC013 -->
        <test-method status="FAIL" signature="HS_Premise_Home_Phone_Check_TC014()[pri:0, instance:exe.HS_Phone_Number_Check_TS006@3ffc5af1]" name="HS_Premise_Home_Phone_Check_TC014" duration-ms="79" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Premise_Home_Phone_Number length not less than 10 Digits expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Premise_Home_Phone_Number length not less than 10 Digits expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Phone_Number_Check_TS006.HS_Premise_Home_Phone_Check_TC014(HS_Phone_Number_Check_TS006.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_Home_Phone_Check_TC014 -->
        <test-method status="FAIL" signature="HS_Premise_Work_Phone_Check_TC015()[pri:0, instance:exe.HS_Phone_Number_Check_TS006@3ffc5af1]" name="HS_Premise_Work_Phone_Check_TC015" duration-ms="20" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Premise_Work_Phone_Number length not less than 10 Digits expected:<0> but was:<1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Premise_Work_Phone_Number length not less than 10 Digits expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Phone_Number_Check_TS006.HS_Premise_Work_Phone_Check_TC015(HS_Phone_Number_Check_TS006.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_Work_Phone_Check_TC015 -->
        <test-method status="FAIL" signature="HS_Premise_Work_Phone_Check_TC016()[pri:0, instance:exe.HS_Phone_Number_Check_TS006@3ffc5af1]" name="HS_Premise_Work_Phone_Check_TC016" duration-ms="28" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Premise_Work_Phone_Number length not less than 10 Digits expected:<0> but was:<1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Premise_Work_Phone_Number length not less than 10 Digits expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Phone_Number_Check_TS006.HS_Premise_Work_Phone_Check_TC016(HS_Phone_Number_Check_TS006.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_Work_Phone_Check_TC016 -->
        <test-method status="PASS" signature="HS_Premise_Work_Phone_Check_TC017()[pri:0, instance:exe.HS_Phone_Number_Check_TS006@3ffc5af1]" name="HS_Premise_Work_Phone_Check_TC017" duration-ms="130" started-at="2017-06-30T19:06:35Z" finished-at="2017-06-30T19:06:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Premise_Work_Phone_Check_TC017 -->
      </class> <!-- exe.HS_Phone_Number_Check_TS006 -->
      <class name="exe.HS_Contract_SchedRef_Check_TS005">
        <test-method status="FAIL" signature="HS_Contract_SchedRef_TC012()[pri:0, instance:exe.HS_Contract_SchedRef_Check_TS005@cc285f4]" name="HS_Contract_SchedRef_TC012" duration-ms="2386" started-at="2017-06-30T19:06:29Z" finished-at="2017-06-30T19:06:31Z">
          <exception class="com.mysql.jdbc.CommunicationsException">
            <message>
              <![CDATA[Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC012(HS_Contract_SchedRef_Check_TS005.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


** END NESTED EXCEPTION **



Last packet sent to the server was 2 ms ago.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC012(HS_Contract_SchedRef_Check_TS005.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


** END NESTED EXCEPTION **



Last packet sent to the server was 2 ms ago.
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2847)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC012(HS_Contract_SchedRef_Check_TS005.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.mysql.jdbc.CommunicationsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Contract_SchedRef_TC012 -->
        <test-method status="FAIL" signature="HS_Contract_SchedRef_TC013()[pri:0, instance:exe.HS_Contract_SchedRef_Check_TS005@cc285f4]" name="HS_Contract_SchedRef_TC013" duration-ms="2008" started-at="2017-06-30T19:06:31Z" finished-at="2017-06-30T19:06:33Z">
          <exception class="com.mysql.jdbc.CommunicationsException">
            <message>
              <![CDATA[Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC013(HS_Contract_SchedRef_Check_TS005.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


** END NESTED EXCEPTION **



Last packet sent to the server was 0 ms ago.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.ConnectException
MESSAGE: Connection refused: connect

STACKTRACE:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:256)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:271)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2771)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC013(HS_Contract_SchedRef_Check_TS005.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


** END NESTED EXCEPTION **



Last packet sent to the server was 0 ms ago.
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2847)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at exe.HS_Contract_SchedRef_Check_TS005.HS_Contract_SchedRef_TC013(HS_Contract_SchedRef_Check_TS005.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.mysql.jdbc.CommunicationsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HS_Contract_SchedRef_TC013 -->
      </class> <!-- exe.HS_Contract_SchedRef_Check_TS005 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
